### ISSUE TITLE
Not functioning in WP 4.9 Multisite

### ISSUE THREAD

**Issue by ratputin** [trepmal/my-sites-search#4]
Just wondering if this has been abandoned. It doesn't seem to work in 4.9.

**Comment by trepmal** [comment]
It's working for me.

Is it consistently not working for you, or only in some sites/screens?

Can you test without plugins and using the default theme to see if the issue persists? Then reactivate one-by-one to see if there's a conflict?

![my-sites-search-wp4 9](https://user-images.githubusercontent.com/251183/34839633-2ad2f4a8-f6b7-11e7-8012-672af8d64e39.png)

**Comment by ratputin** [comment]
I tried it on one of my multisite and it is working there…just not in the one I need it for :). I am sorry, it didn’t occur to me to try it before I posted. Thank you for the quick response. I’ll debug and report back.

KO

**Comment by dmhendricks** [comment]
@ratputin - If you're interested, I forked Kailey's code, tested with WordPress 5:
https://wordpress.org/plugins/my-sites-sort-and-filter/

@trepmal - Thanks for the code! I was sure to give you credit.

**Comment by ratputin** [comment]
Brilliant! Thank you!

KO
