### ISSUE TITLE
Problems with Wordpress 5.5

### ISSUE THREAD

**Issue by shelbybark** [trepmal/my-sites-search#5]
We noticed an issue when our host upgraded our sites to 5.5 last night, and I have determined it is because of lines 112 and 113 of the my-sites-search.php

https://github.com/trepmal/my-sites-search/blob/master/my-sites-search.php#L112-L113

For us, it broke javascript on the Edit Post area of the admin. We initially noticed the Featured Image functionality was not working as intended, and then we noticed we could not use the scheduled post functionality. 

I believe the problem is related to WP 5.5 removing jQuery Migrate.

In my testing, I can get the code to work if I replace 'jquery-core' with either 'jquery' or 'jquery-ui-core' but I'm not sure whether that adds other issues down the road, since it appears 'jquery' loads 1.12.4.

Thanks for the wonderful plugin. It really helps with our multi-site setup.

**Comment by trepmal** [comment]
I think I know that host ;)

Thanks for the report!

This is working on my vanilla 5.5 install, but I'll dig in

**Comment by trepmal** [comment]
Feel free to let me know if the update doesn't work.

**Comment by shelbybark** [comment]
Awesome! Thanks for the quick help today. The fix works great.
