### ISSUE TITLE
Fatal in newer versions of PHP when Admin Bar is shown without a user being logged in.

### ISSUE THREAD

**Issue by emrikol** [trepmal/my-sites-search#6]
`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in plugins/my-sites-search/my-sites-search.php:34`

Casting [`$wp_admin_bar->user->blogs`]([https://github.com/trepmal/my-sites-search/blob/652256957764ea63b6c11f0227e72d4a705defdb/my-sites-search.php#L30]) as an array should fix it :D

**Comment by trepmal** [comment]
should be resolved in 1fa479b9a005b03dd5aa43da49d912f330677fc1
